# Generated by Django 5.2.3 on 2026-07-22 09:08
# ruff: noqa: E501

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nom')),
                ('institution_type', models.CharField(choices=[('PRIMARY_SCHOOL', 'École primaire'), ('MIDDLE_SCHOOL', 'Collège'), ('HIGH_SCHOOL', 'Lycée'), ('AGRICULTURAL', 'Établissement agricole'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name="type d'établissement")),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('postal_code', models.CharField(db_index=True, max_length=10, verbose_name='code postal')),
                ('city', models.CharField(db_index=True, max_length=120, verbose_name='ville')),
                ('department', models.CharField(db_index=True, max_length=3, verbose_name='département')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('administrative_email', models.EmailField(blank=True, max_length=254, verbose_name='courriel administratif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
                'ordering': ('name', 'postal_code', 'city'),
                'indexes': [models.Index(fields=['name', 'postal_code'], name='institution_name_postal_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='courriel')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='inscriptions.institution', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'professeur',
                'verbose_name_plural': 'professeurs',
                'ordering': ('last_name', 'first_name', 'email'),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='référence')),
                ('group_name', models.CharField(max_length=150, verbose_name='nom du groupe')),
                ('student_count', models.PositiveSmallIntegerField(verbose_name="nombre d'élèves")),
                ('chaperone_count', models.PositiveSmallIntegerField(default=0, verbose_name="nombre d'accompagnateurs")),
                ('visit_date', models.DateField(db_index=True, verbose_name='jour de visite')),
                ('special_needs', models.TextField(blank=True, verbose_name='besoins particuliers')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], db_index=True, default='DRAFT', max_length=10, verbose_name='statut')),
                ('draft_expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expiration du brouillon')),
                ('edit_token_digest', models.CharField(editable=False, max_length=64, unique=True, verbose_name='empreinte du jeton de modification')),
                ('token_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='jeton créé le')),
                ('token_revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='jeton révoqué le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmée le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='inscriptions.institution', verbose_name='établissement')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.schoollevel', verbose_name='niveau scolaire')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='inscriptions.teacher', verbose_name='professeur')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Création'), ('CONFIRMED', 'Confirmation'), ('UPDATED', 'Modification'), ('CANCELLED', 'Annulation'), ('TOKEN_ROTATED', 'Renouvellement du lien'), ('EMAIL_SENT', 'Courriel envoyé'), ('EMAIL_FAILED', 'Échec du courriel')], max_length=20, verbose_name='type')),
                ('actor_kind', models.CharField(choices=[('TEACHER', 'Professeur'), ('STAFF', 'Équipe'), ('SYSTEM', 'Système')], max_length=10, verbose_name='acteur')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_events', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inscriptions.registration', verbose_name='inscription')),
            ],
            options={
                'verbose_name': "événement d'inscription",
                'verbose_name_plural': "événements d'inscription",
                'ordering': ('created_at', 'pk'),
                'indexes': [models.Index(fields=['registration', 'created_at'], name='inscription_registr_c02261_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveSmallIntegerField(verbose_name="nombre d'élèves")),
                ('chaperone_count', models.PositiveSmallIntegerField(default=0, verbose_name="nombre d'accompagnateurs")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Annulée')], db_index=True, default='ACTIVE', max_length=10, verbose_name='statut')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inscriptions.registration', verbose_name='inscription')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalogue.session', verbose_name='séance')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ('session__date', 'session__starts_at', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('student_count__gt', 0)), name='reservation_students_positive'), models.CheckConstraint(condition=models.Q(('chaperone_count__gte', 0)), name='reservation_chaperones_nonnegative'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('registration', 'session'), name='one_active_reservation_per_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(('student_count__gt', 0)), name='registration_students_positive'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(('chaperone_count__gte', 0)), name='registration_chaperones_nonnegative'),
        ),
    ]
