# Generated by Django 5.2.3 on 2026-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='anonymisée le'),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Création'), ('CONFIRMED', 'Confirmation'), ('UPDATED', 'Modification'), ('CANCELLED', 'Annulation'), ('TOKEN_ROTATED', 'Renouvellement du lien'), ('EMAIL_SENT', 'Courriel envoyé'), ('EMAIL_FAILED', 'Échec du courriel'), ('ANONYMIZED', 'Anonymisation')], max_length=20, verbose_name='type'),
        ),
    ]
