# Generated by Django 5.2.3 on 2026-07-22 11:16

import hashlib

import django.db.models.deletion
from django.db import migrations, models

FOODS = (
    "abricot",
    "amande",
    "basilic",
    "cacao",
    "cannelle",
    "carotte",
    "cerise",
    "citron",
    "fenouil",
    "figue",
    "fraise",
    "framboise",
    "gingembre",
    "grenade",
    "lentille",
    "menthe",
    "myrtille",
    "noisette",
    "olive",
    "orange",
    "paprika",
    "persil",
    "piment",
    "pistache",
    "poire",
    "pomme",
    "potiron",
    "prune",
    "radis",
    "romarin",
    "safran",
    "sauge",
    "thym",
    "tomate",
    "truffe",
    "vanille",
)
QUALIFIERS = (
    "ambre",
    "argente",
    "boise",
    "brillant",
    "dore",
    "doux",
    "epice",
    "etoile",
    "fleuri",
    "fruite",
    "joyeux",
    "mielleux",
    "nacre",
    "parfume",
    "petillant",
    "sauvage",
    "solaire",
    "tendre",
    "vermeil",
    "vif",
)


def backfill_group_fields(apps, schema_editor):
    GroupFamily = apps.get_model("inscriptions", "GroupFamily")
    Registration = apps.get_model("inscriptions", "Registration")
    fallback_family, _created = GroupFamily.objects.get_or_create(
        slug="non-renseignee",
        defaults={"name": "Non renseignée", "sort_order": 999},
    )
    used_codes = set(
        Registration.objects.exclude(group_code__isnull=True)
        .exclude(group_code="")
        .values_list("group_code", flat=True)
    )
    registrations = list(Registration.objects.order_by("pk"))
    for registration in registrations:
        if not registration.family_id:
            registration.family_id = fallback_family.pk
        if registration.group_code:
            continue
        attempt = 0
        while True:
            digest = hashlib.sha256(f"{registration.reference}:{attempt}".encode("ascii")).digest()
            base_candidate = (
                f"{FOODS[digest[0] % len(FOODS)]}-{QUALIFIERS[digest[1] % len(QUALIFIERS)]}"
            )
            candidate = base_candidate
            if candidate in used_codes:
                candidate = f"{base_candidate}-{FOODS[digest[2] % len(FOODS)]}"
            if candidate not in used_codes:
                registration.group_code = candidate
                used_codes.add(candidate)
                break
            attempt += 1
    if registrations:
        Registration.objects.bulk_update(registrations, ("group_code", "family"))


def reverse_group_backfill(apps, schema_editor):
    Registration = apps.get_model("inscriptions", "Registration")
    Registration.objects.update(group_code=None, family=None)


class Migration(migrations.Migration):
    dependencies = [
        ("inscriptions", "0002_registration_anonymized_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nom")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="identifiant")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "famille de groupe",
                "verbose_name_plural": "familles de groupes",
                "ordering": ("sort_order", "name", "pk"),
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="group_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="code du groupe",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="level_comment",
            field=models.TextField(blank=True, verbose_name="remarque sur le niveau"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="adresse"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="postal_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, verbose_name="code postal"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="inscriptions.groupfamily",
                verbose_name="famille",
            ),
        ),
        migrations.RunPython(backfill_group_fields, reverse_group_backfill),
        migrations.AlterField(
            model_name="registration",
            name="group_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=80,
                unique=True,
                verbose_name="code du groupe",
            ),
        ),
    ]
