# Generated by Django 5.2 for the catalogue application.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nom")),
                ("slug", models.SlugField(unique=True, verbose_name="identifiant URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SchoolLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True, verbose_name="code")),
                ("label", models.CharField(max_length=100, verbose_name="libellé")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre d’affichage"),
                ),
            ],
            options={
                "verbose_name": "niveau scolaire",
                "verbose_name_plural": "niveaux scolaires",
                "ordering": ("sort_order", "label", "code"),
            },
        ),
        migrations.CreateModel(
            name="Animation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="identifiant URL"),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="description courte"),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "indicative_duration",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="durée indicative (minutes)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="animations/", verbose_name="image"),
                ),
                ("instructions", models.TextField(blank=True, verbose_name="consignes")),
                ("accessibility", models.TextField(blank=True, verbose_name="accessibilité")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animations",
                        to="catalogue.category",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "recommended_levels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="animations",
                        to="catalogue.schoollevel",
                        verbose_name="niveaux conseillés",
                    ),
                ),
            ],
            options={
                "verbose_name": "animation",
                "verbose_name_plural": "animations",
                "ordering": ("title", "pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("indicative_duration__gt", 0)),
                        name="cat_animation_duration_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                ("starts_at", models.TimeField(verbose_name="heure de début")),
                ("ends_at", models.TimeField(verbose_name="heure de fin")),
                ("location", models.CharField(max_length=200, verbose_name="lieu")),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="capacité maximale",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouverte"),
                            ("CLOSED", "Fermée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "organizer",
                    models.CharField(blank=True, max_length=200, verbose_name="organisateur"),
                ),
                (
                    "internal_comment",
                    models.TextField(blank=True, verbose_name="commentaire interne"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "animation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="catalogue.animation",
                        verbose_name="animation",
                    ),
                ),
            ],
            options={
                "verbose_name": "séance",
                "verbose_name_plural": "séances",
                "ordering": ("date", "starts_at", "ends_at", "animation__title", "pk"),
                "indexes": [
                    models.Index(fields=["date", "starts_at"], name="cat_session_date_start_idx"),
                    models.Index(fields=["date", "status"], name="cat_session_date_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_capacity__gt", 0)),
                        name="cat_session_capacity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="cat_session_end_after_start",
                    ),
                ],
            },
        ),
    ]
