# Generated by Django 5.2.3 on 2026-07-22 09:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(models.F('animation'), models.F('date'), models.F('starts_at'), models.F('ends_at'), django.db.models.functions.text.Lower('location'), name='cat_session_unique_schedule_location'),
        ),
    ]
