# Generated by Django 5.2.3 on 2026-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_session_cat_session_unique_schedule_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="organizer_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="courriel du responsable"
            ),
        ),
    ]
