# Generated by Django 5.2.3 on 2026-07-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONFIRMATION", "Confirmation"),
                            ("MODIFICATION", "Modification"),
                            ("CANCELLATION", "Annulation"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="destinataire"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SENT", "Envoyé"),
                            ("FAILED", "Échec"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="identifiant fournisseur",
                    ),
                ),
                (
                    "error_summary",
                    models.TextField(blank=True, verbose_name="erreur"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="envoyé le"),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="inscriptions.registration",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "courriel envoyé",
                "verbose_name_plural": "courriels envoyés",
                "ordering": ("-created_at",),
            },
        ),
    ]
