# Generated by Django 5.2.3 on 2026-07-22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="clé d’idempotence",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="objet")),
                ("body_html", models.TextField(verbose_name="contenu enrichi nettoyé")),
                ("body_text", models.TextField(verbose_name="contenu texte")),
                (
                    "visit_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="jour filtré",
                    ),
                ),
                (
                    "family_filter",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="identifiant de famille filtrée",
                    ),
                ),
                (
                    "family_label",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="famille filtrée",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SENDING", "En cours d’envoi"),
                            ("SENT", "Envoyé"),
                            ("PARTIAL", "Partiellement envoyé"),
                            ("FAILED", "Échec"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="envoi commencé le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="envoi terminé le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "campagne de publipostage",
                "verbose_name_plural": "campagnes de publipostage",
                "ordering": ("-created_at",),
                "permissions": (("send_mailing", "Peut envoyer un publipostage"),),
            },
        ),
        migrations.CreateModel(
            name="MailingDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[
                            ("TEACHER", "Professeur"),
                            ("ORGANIZER", "Responsable d’animation"),
                        ],
                        max_length=10,
                        verbose_name="type de destinataire",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, verbose_name="destinataire")),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=200, verbose_name="nom du destinataire"),
                ),
                (
                    "dedupe_key",
                    models.CharField(max_length=255, verbose_name="clé de dédoublonnage"),
                ),
                ("context_snapshot", models.JSONField(default=dict, verbose_name="contexte figé")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SENDING", "En cours"),
                            ("SENT", "Envoyé"),
                            ("FAILED", "Échec"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0, verbose_name="tentatives")),
                ("error_summary", models.TextField(blank=True, verbose_name="erreur")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="dernière tentative le",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="envoyé le"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="communication.mailingcampaign",
                        verbose_name="campagne",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_deliveries",
                        to="inscriptions.registration",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "envoi de publipostage",
                "verbose_name_plural": "envois de publipostage",
                "ordering": ("campaign_id", "recipient_kind", "recipient", "pk"),
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="comm_delivery_campaign_st_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "dedupe_key"),
                        name="comm_mailing_delivery_dedupe",
                    )
                ],
            },
        ),
    ]
